### ISSUE TITLE
Member 도메인 JPA 변환

### ISSUE THREAD

**Issue by hjj4060** [ClothingStoreService/clothstar_v2.0#1]
## Description
기존 Member 도메인 JPA 변환 

## Task
- [x] Member, Address, Seller 기존 기능 JPA 동작 가능하게 개발
- [x] JPA로 기존 기능 구현한것 테스트 코드 작성
- [x] 기존 Mybatis 기능 제거
