### ISSUE TITLE
2차 프로젝트 세팅

### ISSUE THREAD

**Issue by hjj4060** [ClothingStoreService/clothstar_v2.0#2]
## Description
1차 프로젝트 레파지토리를 복사하여 2차 프로젝트 진행

## Task
- [x] 1차 프로젝트 복사해서 2차 레파지토리에 복사
- [x] 스프링부트 3점대로 버전 업그레이드
- [x] JPA 의존성 추가
- [x] JPA, Mybatis 동시 사용할수있게 설계진행
